import 'package:flutter/material.dart';
import 'package:coderz1/bloc/models/student_model.dart';
import 'package:coderz1/bloc/models/classroom_model.dart';
import 'package:coderz1/bloc/services/student_api_service.dart';

class AddStudentScreen extends StatefulWidget {
  const AddStudentScreen({super.key});

  @override
  State<AddStudentScreen> createState() => _AddStudentScreenState();
}

class _AddStudentScreenState extends State<AddStudentScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _usernameController = TextEditingController();
  Classroom? _selectedClassroom;
  List<Classroom> _classrooms = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _fetchClassrooms();
  }

  Future<void> _fetchClassrooms() async {
    try {
      final apiService = StudentApiService();
      final classrooms = await apiService.fetchClassrooms();
      setState(() {
        _classrooms = classrooms;
        _isLoading = false;
      });
    } catch (e) {
      // Handle error, e.g., show a snackbar
      print('Failed to load classrooms: $e');
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _addStudent() async {
    if (_formKey.currentState!.validate()) {
      // Create a dummy StudentId as it's usually generated by the backend
      // In a real app, you might not send studentId for new student creation
      final newStudent = Student(
        studentId: 0, // Placeholder, will be ignored by backend for new student
        username: _usernameController.text,
        classroomId: _selectedClassroom!.classroomId,
      );

      try {
        final apiService = StudentApiService();
        await apiService.addStudent(newStudent);
        if (mounted) {
          Navigator.pop(context, true); // Pop with true to indicate success
        }
      } catch (e) {
        // Handle error, e.g., show a snackbar
        print('Failed to add student: $e');
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Failed to add student: $e')));
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add Student'),
      content: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextFormField(
                    controller: _usernameController,
                    decoration: const InputDecoration(labelText: 'Username'),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a username';
                      }
                      return null;
                    },
                  ),
                  DropdownButtonFormField<Classroom>(
                    decoration: const InputDecoration(labelText: 'Classroom'),
                    value: _selectedClassroom,
                    onChanged: (Classroom? newValue) {
                      setState(() {
                        _selectedClassroom = newValue;
                      });
                    },
                    items: _classrooms.map<DropdownMenuItem<Classroom>>((
                      Classroom classroom,
                    ) {
                      return DropdownMenuItem<Classroom>(
                        value: classroom,
                        child: Text(classroom.name),
                      );
                    }).toList(),
                    validator: (value) {
                      if (value == null) {
                        return 'Please select a classroom';
                      }
                      return null;
                    },
                  ),
                ],
              ),
            ),
      actions: [
        TextButton(
          onPressed: () {
            Navigator.pop(context); // Dismiss the dialog
          },
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _isLoading ? null : _addStudent,
          child: const Text('Add'),
        ),
      ],
    );
  }

  @override
  void dispose() {
    _usernameController.dispose();
    super.dispose();
  }
}
